name: check

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup latest deno version
        uses: denoland/setup-deno@v1

      - name: Verify formatting
        run: deno fmt --check

      - name: Verify lint
        run: deno lint
      
      - name: Verify ts
        run: deno check ./cli.ts
