name: release

on:
  workflow_dispatch:
    inputs:
      releaseKind:
        description: "Example of automated release"
        default: "minor"
        type: choice
        options:
          - patch
          - minor
          - major
          - prepatch
          - preminor
          - premajor
          - prerelease
        required: true

jobs:
  release:
    name: version bump and publish
    runs-on: ubuntu-latest
    timeout-minutes: 5

    permissions:
      contents: write
      id-token: write

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Deno
        uses: denoland/setup-deno@v2

      - name: setup git config
        run: |
          git config user.name "@actions"
          git config user.email "spanner@bot"

      - name: Run version bump
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          deno task release ${{github.event.inputs.releaseKind}}

      - name: Publish package
        run: deno publish
